import type { Metadata } from "next";
import { Onest } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "./components/Navbar";

import "./globals.css";

const inter = Onest({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Testimonials",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${inter.className} bg-base-color text-[#fafafa]`}>
          <Navbar />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
